/*
 * This file is generated by jOOQ.
 */
package com.cy.info.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TBook implements Serializable {

    private static final long serialVersionUID = 341545914;

    private final String bookId;
    private final String bookName;
    private final String bookNumber;

    public TBook(TBook value) {
        this.bookId = value.bookId;
        this.bookName = value.bookName;
        this.bookNumber = value.bookNumber;
    }

    public TBook(
        String bookId,
        String bookName,
        String bookNumber
    ) {
        this.bookId = bookId;
        this.bookName = bookName;
        this.bookNumber = bookNumber;
    }

    public String getBookId() {
        return this.bookId;
    }

    public String getBookName() {
        return this.bookName;
    }

    public String getBookNumber() {
        return this.bookNumber;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TBook (");

        sb.append(bookId);
        sb.append(", ").append(bookName);
        sb.append(", ").append(bookNumber);

        sb.append(")");
        return sb.toString();
    }
}
