/*
 * This file is generated by jOOQ.
 */
package com.cy.info.jooq.tables.records;


import com.cy.info.jooq.tables.TBook;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TBookRecord extends UpdatableRecordImpl<TBookRecord> implements Record3<String, String, String> {

    private static final long serialVersionUID = 626442568;

    /**
     * Setter for <code>jooq_demo.t_book.book_id</code>.
     */
    public TBookRecord setBookId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>jooq_demo.t_book.book_id</code>.
     */
    public String getBookId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>jooq_demo.t_book.book_name</code>.
     */
    public TBookRecord setBookName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>jooq_demo.t_book.book_name</code>.
     */
    public String getBookName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>jooq_demo.t_book.book_number</code>.
     */
    public TBookRecord setBookNumber(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>jooq_demo.t_book.book_number</code>.
     */
    public String getBookNumber() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<String, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return TBook.T_BOOK.BOOK_ID;
    }

    @Override
    public Field<String> field2() {
        return TBook.T_BOOK.BOOK_NAME;
    }

    @Override
    public Field<String> field3() {
        return TBook.T_BOOK.BOOK_NUMBER;
    }

    @Override
    public String component1() {
        return getBookId();
    }

    @Override
    public String component2() {
        return getBookName();
    }

    @Override
    public String component3() {
        return getBookNumber();
    }

    @Override
    public String value1() {
        return getBookId();
    }

    @Override
    public String value2() {
        return getBookName();
    }

    @Override
    public String value3() {
        return getBookNumber();
    }

    @Override
    public TBookRecord value1(String value) {
        setBookId(value);
        return this;
    }

    @Override
    public TBookRecord value2(String value) {
        setBookName(value);
        return this;
    }

    @Override
    public TBookRecord value3(String value) {
        setBookNumber(value);
        return this;
    }

    @Override
    public TBookRecord values(String value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TBookRecord
     */
    public TBookRecord() {
        super(TBook.T_BOOK);
    }

    /**
     * Create a detached, initialised TBookRecord
     */
    public TBookRecord(String bookId, String bookName, String bookNumber) {
        super(TBook.T_BOOK);

        set(0, bookId);
        set(1, bookName);
        set(2, bookNumber);
    }
}
