/*
 * This file is generated by jOOQ.
 */
package com.cy.info.jooq;


import com.cy.info.jooq.tables.TBook;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>jooq_demo</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index T_BOOK_PRIMARY = Indexes0.T_BOOK_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index T_BOOK_PRIMARY = Internal.createIndex("PRIMARY", TBook.T_BOOK, new OrderField[] { TBook.T_BOOK.BOOK_ID }, true);
    }
}
