/*
 * This file is generated by jOOQ.
 */
package com.cy.info.jooq;


import com.cy.info.jooq.tables.TBook;
import com.cy.info.jooq.tables.records.TBookRecord;

import javax.annotation.Generated;

import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>jooq_demo</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<TBookRecord> KEY_T_BOOK_PRIMARY = UniqueKeys0.KEY_T_BOOK_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<TBookRecord> KEY_T_BOOK_PRIMARY = Internal.createUniqueKey(TBook.T_BOOK, "KEY_t_book_PRIMARY", TBook.T_BOOK.BOOK_ID);
    }
}
