/*
 * This file is generated by jOOQ.
 */
package com.cy.info.jooq;


import com.cy.info.jooq.tables.TBook;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in jooq_demo
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>jooq_demo.t_book</code>.
     */
    public static final TBook T_BOOK = TBook.T_BOOK;
}
