/*
 * This file is generated by jOOQ.
 */
package com.cy.info.jooq.tables.daos;


import com.cy.info.jooq.tables.TBook;
import com.cy.info.jooq.tables.records.TBookRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TBookDao extends DAOImpl<TBookRecord, com.cy.info.jooq.tables.pojos.TBook, String> {

    /**
     * Create a new TBookDao without any configuration
     */
    public TBookDao() {
        super(TBook.T_BOOK, com.cy.info.jooq.tables.pojos.TBook.class);
    }

    /**
     * Create a new TBookDao with an attached configuration
     */
    public TBookDao(Configuration configuration) {
        super(TBook.T_BOOK, com.cy.info.jooq.tables.pojos.TBook.class, configuration);
    }

    @Override
    public String getId(com.cy.info.jooq.tables.pojos.TBook object) {
        return object.getBookId();
    }

    /**
     * Fetch records that have <code>book_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.cy.info.jooq.tables.pojos.TBook> fetchRangeOfBookId(String lowerInclusive, String upperInclusive) {
        return fetchRange(TBook.T_BOOK.BOOK_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>book_id IN (values)</code>
     */
    public List<com.cy.info.jooq.tables.pojos.TBook> fetchByBookId(String... values) {
        return fetch(TBook.T_BOOK.BOOK_ID, values);
    }

    /**
     * Fetch a unique record that has <code>book_id = value</code>
     */
    public com.cy.info.jooq.tables.pojos.TBook fetchOneByBookId(String value) {
        return fetchOne(TBook.T_BOOK.BOOK_ID, value);
    }

    /**
     * Fetch records that have <code>book_name BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.cy.info.jooq.tables.pojos.TBook> fetchRangeOfBookName(String lowerInclusive, String upperInclusive) {
        return fetchRange(TBook.T_BOOK.BOOK_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>book_name IN (values)</code>
     */
    public List<com.cy.info.jooq.tables.pojos.TBook> fetchByBookName(String... values) {
        return fetch(TBook.T_BOOK.BOOK_NAME, values);
    }

    /**
     * Fetch records that have <code>book_number BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.cy.info.jooq.tables.pojos.TBook> fetchRangeOfBookNumber(String lowerInclusive, String upperInclusive) {
        return fetchRange(TBook.T_BOOK.BOOK_NUMBER, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>book_number IN (values)</code>
     */
    public List<com.cy.info.jooq.tables.pojos.TBook> fetchByBookNumber(String... values) {
        return fetch(TBook.T_BOOK.BOOK_NUMBER, values);
    }
}
